# Generated by Django 6.0.6 on 2026-06-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reference',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
